### ISSUE TITLE
Rename and register?

### ISSUE THREAD

**Issue by jw3126** [goretkin/FixArgs.jl#6]
I think it would be nice if the package was registered. I know the plan is that this lands in base, but that can take like a year until it ships with the stable julia version. Maybe `Curry.jl` is not an ideal name though. What about `ArgFix.jl`?

**Comment by goretkin** [comment]
I don't like `Curry.jl` that much,  but I was motivated to choose `Curry.jl` because it was a short name that is sort-of related and would pass the automatic registration requirements (afaik).

Thanks for suggesting `ArgFix.jl`. It is also very short and has a better chance of being descriptive than "Curry". I also have mixed feelings about that name, because it makes me think of "command line arguments" (e.g. `ArgParse.jl`) and not of "function arguments". 

I was curious to see what currently registered names with `Arg` are about https://juliahub.com/ui/Packages?q=Arg

command-line arguments
https://juliahub.com/ui/Packages/ArgParse/apuSZ
https://juliahub.com/ui/Packages/ArgMacros/aUDMk

function arguments
https://juliahub.com/ui/Packages/ArgCheck/P66Js (hi!!)
https://juliahub.com/ui/Packages/ArgTools/aGHFV

And that's all I found, so it's not like there's a particularly strong precedent that `Arg` means "command-line argument".

Also worth considering that (fundamentally) this package introduces a type that is currently called `Fix`, and that that many packages like that just pluralize the type name (e.g `OffsetArrays.jl`).

After brief consideration, I am just about ready to rename to `ArgFix.jl`, but I'll wait a bit in case any other ideas emerge. Thanks again for your help and interest!

**Comment by goretkin** [comment]
branch names master -> main
package name: Curry.jl -> FixArgs.jl

The docs will get triggered later I think.

**Comment by tpapp** [comment]
The docs still seems to have the old name.

**Comment by goretkin** [comment]
Docs are now getting deployed correctly, and registration is underway: https://github.com/JuliaRegistries/General/pull/24349
